"""The provisioning proxy and its internal network (design plan §0 decision
2-3, chunk S2): a tinyproxy container that is the only route out of the
``--internal`` network a provisioning build or ``uv add`` runs on.

Bypass is impossible by construction — an internal network has no gateway
— so the proxy's job is to *narrow* what the allowed route reaches: it
accepts ``CONNECT <host>:443`` for the hosts of the generated allow-list
(``guru.config.ALLOWED_DOMAINS``, the project's domain approvals; no
second list, no implicit additions — ``pypi.org`` and
``files.pythonhosted.org`` must both be approved) and refuses everything
else: other hosts, other ports (``ConnectPort 443``), and plain HTTP
(``FilterURLs On`` with anchored ``^host:443$`` patterns never match a
``http://`` URL; ``FilterDefaultDeny Yes``). Every request is logged
(``LogLevel Connect``) to the container's stdout/stderr, which
:func:`tail_access_log` reads and parses into ``net_events`` rows.

Every docker invocation is a fixed argv through ``guru.domain.procs.run``
with :func:`guru.sandbox.colima.docker_env`. The proxy container runs the
image's unprivileged user, read-only, all capabilities dropped, with the
generated config bind-mounted read-only. It is attached to the internal
network at start and then connected to the default ``bridge`` for its
external route; ``Allow <client_cidr>`` (the internal subnet) keeps other
bridge containers from using it.
"""
from __future__ import annotations

import ipaddress
import re
from pathlib import Path
from typing import Iterable, Optional

from guru import log
from guru.domain import procs
from guru.domain.procs import ProcResult
from guru.sandbox.colima import DOCKER, _limits, docker_env

PROXY_PORT = 8888
PROXY_PIDS = 64
PROXY_MEMORY_MB = 128
CONFIG_MOUNT = '/config'
CONF_FILE = 'tinyproxy.conf'
FILTER_FILE = 'filter'
TINYPROXY_BIN = '/usr/bin/tinyproxy'
BRIDGE = 'bridge'
CONNECT_PORT = 443
NETWORK_TIMEOUT_S = 30
RUN_TIMEOUT_S = 60
LOGS_TIMEOUT_S = 30
LOGS_OUT_KB = 4096
_HOST_RX = re.compile(r'(?=.{1,253}\Z)[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?'
                      r'(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*')
_LOG_RX = re.compile(r'^(?P<level>[A-Z]+)\s+(?P<ts>[A-Z][a-z]{2} \d\d? '
                     r'\d\d:\d\d:\d\d(?:\.\d+)?) \[\d+\]: (?P<msg>.*)$')
_REQUEST_RX = re.compile(r'^Request \(file descriptor \d+\): '
                         r'(?P<method>[A-Z]+) (?P<url>\S+)(?: HTTP/\S+)?$')
_ESTABLISHED_RX = re.compile(r'^Established connection to host '
                             r'"(?P<host>[^"]+)"')
_REFUSED_RX = re.compile(r'^Proxying refused on filtered '
                         r'(?:url|domain) "(?P<url>[^"]*)"')
NO_UPSTREAM = 'no upstream connection'


class ProxyError(RuntimeError):
    """The network or the proxy container could not be brought up."""


# --- allow-list and config ---------------------------------------------------

def allowlist_from_domains(domains: Iterable[str]) -> list[str]:
    """The proxy's host allow-list from a domain set: stripped,
    lower-cased, de-duplicated, sorted. Nothing is added implicitly (in
    particular ``pypi.org`` does not imply ``files.pythonhosted.org``: the
    user approves both). An entry that is not a hostname is dropped with a
    warning — it cannot be CONNECTed to and must not reach the config."""
    out: set[str] = set()
    for raw in domains:
        host = str(raw).strip().lower()
        if not host:
            continue
        if not _HOST_RX.fullmatch(host):
            log.warning('sandbox proxy: ignoring malformed allow-list entry '
                        '%r', raw)
            continue
        out.add(host)
    return sorted(out)


def render_filter(allowlist: list[str]) -> str:
    """The tinyproxy filter file: one anchored extended-regex per host,
    ``^host:443$`` — the exact request-URI of ``CONNECT host:443``. A
    plain-HTTP URL (``http://host/…``) or another port never matches."""
    return ''.join(f'^{re.escape(host)}:{CONNECT_PORT}$\n'
                   for host in allowlist)


def render_config(allowlist: list[str], client_cidr: str = '') -> str:
    """``tinyproxy.conf`` for ``allowlist``: listen on ``PROXY_PORT`` on all
    interfaces, log every request at ``Connect`` level to stdout (no
    ``LogFile``), refuse ``CONNECT`` to any port but 443, filter request
    URLs against :func:`render_filter` with deny-by-default, no Via header.
    ``client_cidr`` (the internal network's subnet) becomes the only
    ``Allow`` line; without it every client is accepted. ``ValueError``
    for a malformed CIDR."""
    lines = [
        '# Generated by guru (guru.sandbox.proxy.render_config); do not edit.',
        '# Allowed CONNECT targets (port 443 only): '
        + (', '.join(allowlist) or '(none)'),
        f'Port {PROXY_PORT}',
        'Listen 0.0.0.0',
        'Timeout 300',
        f'MaxClients {PROXY_PIDS}',
        'LogLevel Connect',
        'DisableViaHeader Yes',
    ]
    if client_cidr:
        network = ipaddress.ip_network(client_cidr, strict=False)
        lines.append(f'Allow {network}')
    lines += [
        f'ConnectPort {CONNECT_PORT}',
        'FilterURLs On',
        'FilterType ere',
        'FilterCaseSensitive Off',
        'FilterDefaultDeny Yes',
        f'Filter "{CONFIG_MOUNT}/{FILTER_FILE}"',
        '',
    ]
    return '\n'.join(lines)


def write_config(config_dir: Path, allowlist: list[str],
                 client_cidr: str = '') -> Path:
    """Write ``CONF_FILE`` and ``FILTER_FILE`` into ``config_dir`` (created)
    and return the config path."""
    root = Path(config_dir)
    root.mkdir(parents=True, exist_ok=True)
    (root / FILTER_FILE).write_text(render_filter(allowlist),
                                    encoding='utf-8')
    conf = root / CONF_FILE
    conf.write_text(render_config(allowlist, client_cidr), encoding='utf-8')
    return conf


# --- docker plumbing ---------------------------------------------------------

def _docker(args: list[str], cwd: Optional[Path], timeout_s: int,
            out_kb: int = 64) -> ProcResult:
    where = Path(cwd) if cwd is not None else Path.cwd()
    return procs.run([DOCKER, *args], where, _limits(timeout_s, out_kb),
                     env_extra=docker_env())


def _failed(res: ProcResult) -> str:
    return (res.denied or res.stderr.strip() or res.stdout.strip()
            or f'exit {res.returncode}')[:400]


def network_up(name: str, cwd: Optional[Path] = None) -> None:
    """``docker network create --internal <name>``; an existing network of
    that name is reused. ``ProxyError`` otherwise."""
    res = _docker(['network', 'create', '--internal', name], cwd,
                  NETWORK_TIMEOUT_S)
    if res.returncode == 0 and not res.denied:
        return
    if 'already exists' in res.stderr:
        log.info('sandbox proxy: reusing existing network %s', name)
        return
    raise ProxyError(f'docker network create {name} failed: {_failed(res)}')


def network_down(name: str, cwd: Optional[Path] = None) -> None:
    """``docker network rm <name>``; a failure is logged, never raised."""
    res = _docker(['network', 'rm', name], cwd, NETWORK_TIMEOUT_S)
    if res.returncode != 0 or res.denied:
        log.warning('sandbox proxy: docker network rm %s failed: %s', name,
                    _failed(res))


def network_subnet(name: str, cwd: Optional[Path] = None) -> str:
    """The network's first IPAM subnet (``172.25.0.0/16``), or ``''``."""
    res = _docker(['network', 'inspect', '--format',
                   '{{(index .IPAM.Config 0).Subnet}}', name], cwd,
                  NETWORK_TIMEOUT_S)
    if res.returncode != 0 or res.denied:
        return ''
    subnet = res.stdout.strip()
    try:
        ipaddress.ip_network(subnet, strict=False)
    except ValueError:
        return ''
    return subnet


def proxy_run_argv(name: str, network: str, config_dir: Path, image: str
                   ) -> list[str]:
    """The exact ``docker run`` argv for the proxy container (pure)."""
    return [DOCKER, 'run', '-d', '--rm', '--name', name,
            '--network', network,
            '--cap-drop', 'ALL', '--security-opt', 'no-new-privileges',
            '--read-only', '--tmpfs', '/tmp',
            '--pids-limit', str(PROXY_PIDS),
            '--memory', f'{PROXY_MEMORY_MB}m',
            '-v', f'{Path(config_dir)}:{CONFIG_MOUNT}:ro',
            image, TINYPROXY_BIN, '-d', '-c', f'{CONFIG_MOUNT}/{CONF_FILE}']


def proxy_up(name: str, network: str, config_dir: Path, image: str,
             cwd: Optional[Path] = None) -> str:
    """Start the proxy container ``name`` on the internal ``network`` with
    ``config_dir`` (see :func:`write_config`) mounted read-only, connect
    it to the default bridge for its external route, and confirm it is
    running. A stale container of that name is removed first. Returns the
    container name; on any failure the container is removed and
    ``ProxyError`` raised."""
    proxy_down(name, cwd, quiet=True)
    argv = proxy_run_argv(name, network, Path(config_dir), image)
    res = procs.run(argv, Path(cwd) if cwd is not None else Path.cwd(),
                    _limits(RUN_TIMEOUT_S, 64), env_extra=docker_env())
    if res.returncode != 0 or res.denied:
        proxy_down(name, cwd, quiet=True)
        raise ProxyError(f'proxy container {name} failed to start: '
                         f'{_failed(res)}')
    try:
        connect = _docker(['network', 'connect', BRIDGE, name], cwd,
                          NETWORK_TIMEOUT_S)
        if connect.returncode != 0 or connect.denied:
            raise ProxyError(f'proxy container {name}: docker network '
                             f'connect {BRIDGE} failed: {_failed(connect)}')
        state = _docker(['inspect', '--format', '{{.State.Running}}', name],
                        cwd, NETWORK_TIMEOUT_S)
        if state.stdout.strip() != 'true':
            raise ProxyError(f'proxy container {name} is not running: '
                             f'{_failed(state)}')
    except ProxyError:
        proxy_down(name, cwd, quiet=True)
        raise
    return name


def proxy_down(name: str, cwd: Optional[Path] = None,
               quiet: bool = False) -> None:
    """``docker rm -f <name>``; a failure is logged (unless ``quiet``),
    never raised."""
    res = _docker(['rm', '-f', name], cwd, NETWORK_TIMEOUT_S)
    if (res.returncode != 0 or res.denied) and not quiet:
        log.warning('sandbox proxy: docker rm -f %s failed: %s', name,
                    _failed(res))


# --- access log --------------------------------------------------------------

def _split_target(method: str, url: str) -> tuple[str, int]:
    """``(host, port)`` of a request-URI: ``host:port`` for CONNECT, a
    URL otherwise (default port by scheme)."""
    if method == 'CONNECT':
        host, _, port = url.rpartition(':')
        if host and port.isdigit():
            return host.lower(), int(port)
        return url.lower(), CONNECT_PORT
    scheme, sep, rest = url.partition('://')
    if not sep:
        return url.lower(), 80
    authority = rest.split('/', 1)[0]
    host, _, port = authority.rpartition(':')
    if host and port.isdigit():
        return host.lower(), int(port)
    return authority.lower(), 443 if scheme.lower() == 'https' else 80


def parse_log(text: str) -> list[dict]:
    """Parse tinyproxy's log into one dict per request — ``ts``,
    ``method``, ``host``, ``port``, ``url``, ``allowed``, ``reason`` — in
    request order. A request is *allowed* when a later ``Established
    connection to host "<host>"`` line pairs with it (oldest pending request
    for that host first; the proxy serves clients concurrently so
    line order alone is not reliable), *denied* with reason ``filtered``
    when a ``Proxying refused`` line names its URL, and otherwise denied
    with ``NO_UPSTREAM`` (a port ``ConnectPort`` refused, or a connect
    that never completed)."""
    rows: list[dict] = []
    pending: list[dict] = []
    for raw in (text or '').splitlines():
        m = _LOG_RX.match(raw.strip())
        if not m:
            continue
        msg = m.group('msg')
        req = _REQUEST_RX.match(msg)
        if req:
            host, port = _split_target(req.group('method'), req.group('url'))
            row = {'ts': m.group('ts'), 'method': req.group('method'),
                   'host': host, 'port': port, 'url': req.group('url'),
                   'allowed': False, 'reason': NO_UPSTREAM}
            rows.append(row)
            pending.append(row)
            continue
        est = _ESTABLISHED_RX.match(msg)
        if est:
            host = est.group('host').lower()
            for row in pending:
                if row['host'] == host and row['method'] == 'CONNECT':
                    row['allowed'], row['reason'] = True, ''
                    pending.remove(row)
                    break
            continue
        ref = _REFUSED_RX.match(msg)
        if ref:
            url = ref.group('url')
            for row in pending:
                if row['url'] == url:
                    row['reason'] = 'filtered'
                    pending.remove(row)
                    break
    return rows


def tail_access_log(name: str, since: str = '',
                    cwd: Optional[Path] = None) -> list[dict]:
    """``docker logs [--since <since>] <name>`` parsed with
    :func:`parse_log` (stdout and stderr both; tinyproxy writes to stderr
    when it has no ``LogFile``). Empty when the container is gone."""
    args = ['logs', *(['--since', since] if since else []), name]
    res = _docker(args, cwd, LOGS_TIMEOUT_S, out_kb=LOGS_OUT_KB)
    if res.returncode != 0 or res.denied:
        log.warning('sandbox proxy: docker logs %s failed: %s', name,
                    _failed(res))
        return []
    return parse_log(res.stdout + '\n' + res.stderr)
